### ISSUE TITLE
你好，如何处理android或ios上未安装支付宝app的情况？

### ISSUE THREAD

**Issue by zituocn** [lishuhao/sy_flutter_alipay#5]
如题，
目前在android上，如果未安装支付宝app，会闪退。

异常信息：

E/libc    (31011): Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
W/RenderThread(31011): type=1400 audit(0.0:1858): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=14862 scontext=u:r:untrusted_app:s0:c168,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
W/System.err(31011): java.lang.SecurityException: getDeviceId
W/System.err(31011): 	at android.os.Parcel.createException(Parcel.java:1950)
W/System.err(31011): 	at android.os.Parcel.readException(Parcel.java:1918)
W/System.err(31011): 	at android.os.Parcel.readException(Parcel.java:1868)
W/System.err(31011): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:5407)
W/System.err(31011): 	at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1240)
W/System.err(31011): 	at com.alipay.sdk.util.a.<init>(SourceFile:38)
W/System.err(31011): 	at com.alipay.sdk.util.a.a(SourceFile:27)
W/System.err(31011): 	at com.alipay.sdk.tid.b.a(SourceFile:79)
W/System.err(31011): 	at com.alipay.sdk.app.statistic.c.<init>(SourceFile:1229)
W/System.err(31011): 	at com.alipay.sdk.app.statistic.a.a(SourceFile:21)
W/System.err(31011): 	at com.alipay.sdk.app.PayTask.<init>(SourceFile:58)
W/System.err(31011): 	at alipay.flutter.isanye.cn.syflutteralipay.SyFlutterAlipayPlugin$1.run(SyFlutterAlipayPlugin.java:60)
W/System.err(31011): 	at java.lang.Thread.run(Thread.java:764)
W/Thread-2(31011): type=1400 audit(0.0:1859): avc: denied { read } for name="version" dev="proc" ino=4026532066 scontext=u:r:untrusted_app:s0:c168,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0
E/AndroidRuntime(31011): FATAL EXCEPTION: Thread-2
E/AndroidRuntime(31011): Process: net.zituo.scc.flutter_demo, PID: 31011
E/AndroidRuntime(31011): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(31011): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:135)
E/AndroidRuntime(31011): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/AndroidRuntime(31011): 	at alipay.flutter.isanye.cn.syflutteralipay.SyFlutterAlipayPlugin$1.run(SyFlutterAlipayPlugin.java:65)
E/AndroidRuntime(31011): 	at java.lang.Thread.run(Thread.java:764)
I/Process (31011): Sending signal. PID: 31011 SIG: 9

**Comment by shabake** [comment]
解决了吗
